name: autofill_webview
description: A Flutter application for autofilling web forms.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted based on typical Flutter 3.x requirements

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.0.0
  provider: ^6.0.0
  flutter_secure_storage: ^8.0.0 # Matched version from PDR
  file_picker: ^5.2.0
  flutter_json_view: ^1.0.0 # Matched version from PDR

  cupertino_icons: ^1.0.2 # Common Flutter dependency

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Or a newer version, good practice

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/autofill.js
  #   - images/a_dot_ham.jpeg

  # An example font in this section indicates how to
  # remove this file and regenerate the fonts.gif file ("flutter pub run
  # fonts_goldens.dart") was generated by this script.
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
